;;;; T^4 para 66.09 Laboratorio de Microcomputadoras
;;;; Por Mariano Beiró y Mariano Chouza
;;;; Header para las variables

EXTRN DATA(board_line)
EXTRN DATA(line_num)
EXTRN DATA(linea_0)
EXTRN DATA(linea_1)
EXTRN DATA(linea_2)
EXTRN DATA(jugar)
EXTRN DATA(cmt_ptr)
EXTRN DATA(cmt_bit_offset)
EXTRN DATA(cmt_byte_buffer)
EXTRN DATA(buffer)

EXTRN DATA(estado_melodia)
EXTRN DATA(nota_actual)
EXTRN DATA(timer_nota_actual)

EXTRN IDATA(stack)
